/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MintCircuitGroth16VerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALPHA_X"
      | "ALPHA_Y"
      | "BASE_FIELD_SIZE"
      | "BETA_X1"
      | "BETA_X2"
      | "BETA_Y1"
      | "BETA_Y2"
      | "DELTA_X1"
      | "DELTA_X2"
      | "DELTA_Y1"
      | "DELTA_Y2"
      | "GAMMA_X1"
      | "GAMMA_X2"
      | "GAMMA_Y1"
      | "GAMMA_Y2"
      | "IC0_X"
      | "IC0_Y"
      | "IC10_X"
      | "IC10_Y"
      | "IC11_X"
      | "IC11_Y"
      | "IC12_X"
      | "IC12_Y"
      | "IC13_X"
      | "IC13_Y"
      | "IC14_X"
      | "IC14_Y"
      | "IC15_X"
      | "IC15_Y"
      | "IC16_X"
      | "IC16_Y"
      | "IC17_X"
      | "IC17_Y"
      | "IC18_X"
      | "IC18_Y"
      | "IC19_X"
      | "IC19_Y"
      | "IC1_X"
      | "IC1_Y"
      | "IC20_X"
      | "IC20_Y"
      | "IC21_X"
      | "IC21_Y"
      | "IC22_X"
      | "IC22_Y"
      | "IC23_X"
      | "IC23_Y"
      | "IC24_X"
      | "IC24_Y"
      | "IC2_X"
      | "IC2_Y"
      | "IC3_X"
      | "IC3_Y"
      | "IC4_X"
      | "IC4_Y"
      | "IC5_X"
      | "IC5_Y"
      | "IC6_X"
      | "IC6_Y"
      | "IC7_X"
      | "IC7_Y"
      | "IC8_X"
      | "IC8_Y"
      | "IC9_X"
      | "IC9_Y"
      | "P_TOTAL_SIZE"
      | "SCALAR_FIELD_SIZE"
      | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ALPHA_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "ALPHA_Y", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BASE_FIELD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BETA_X1", values?: undefined): string;
  encodeFunctionData(functionFragment: "BETA_X2", values?: undefined): string;
  encodeFunctionData(functionFragment: "BETA_Y1", values?: undefined): string;
  encodeFunctionData(functionFragment: "BETA_Y2", values?: undefined): string;
  encodeFunctionData(functionFragment: "DELTA_X1", values?: undefined): string;
  encodeFunctionData(functionFragment: "DELTA_X2", values?: undefined): string;
  encodeFunctionData(functionFragment: "DELTA_Y1", values?: undefined): string;
  encodeFunctionData(functionFragment: "DELTA_Y2", values?: undefined): string;
  encodeFunctionData(functionFragment: "GAMMA_X1", values?: undefined): string;
  encodeFunctionData(functionFragment: "GAMMA_X2", values?: undefined): string;
  encodeFunctionData(functionFragment: "GAMMA_Y1", values?: undefined): string;
  encodeFunctionData(functionFragment: "GAMMA_Y2", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC0_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC0_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC10_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC10_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC11_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC11_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC12_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC12_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC13_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC13_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC14_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC14_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC15_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC15_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC16_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC16_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC17_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC17_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC18_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC18_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC19_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC19_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC1_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC1_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC20_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC20_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC21_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC21_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC22_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC22_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC23_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC23_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC24_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC24_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC2_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC2_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC3_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC3_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC4_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC4_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC5_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC5_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC6_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC6_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC7_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC7_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC8_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC8_Y", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC9_X", values?: undefined): string;
  encodeFunctionData(functionFragment: "IC9_Y", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "P_TOTAL_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SCALAR_FIELD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "ALPHA_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ALPHA_Y", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BASE_FIELD_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BETA_X1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BETA_X2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BETA_Y1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BETA_Y2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DELTA_X1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DELTA_X2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DELTA_Y1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DELTA_Y2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GAMMA_X1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GAMMA_X2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GAMMA_Y1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GAMMA_Y2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC0_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC0_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC10_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC10_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC11_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC11_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC12_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC12_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC13_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC13_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC14_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC14_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC15_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC15_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC16_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC16_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC17_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC17_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC18_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC18_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC19_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC19_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC1_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC1_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC20_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC20_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC21_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC21_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC22_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC22_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC23_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC23_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC24_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC24_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC2_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC2_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC3_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC3_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC4_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC4_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC5_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC5_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC6_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC6_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC7_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC7_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC8_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC8_Y", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC9_X", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IC9_Y", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "P_TOTAL_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SCALAR_FIELD_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export interface MintCircuitGroth16Verifier extends BaseContract {
  connect(runner?: ContractRunner | null): MintCircuitGroth16Verifier;
  waitForDeployment(): Promise<this>;

  interface: MintCircuitGroth16VerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALPHA_X: TypedContractMethod<[], [bigint], "view">;

  ALPHA_Y: TypedContractMethod<[], [bigint], "view">;

  BASE_FIELD_SIZE: TypedContractMethod<[], [bigint], "view">;

  BETA_X1: TypedContractMethod<[], [bigint], "view">;

  BETA_X2: TypedContractMethod<[], [bigint], "view">;

  BETA_Y1: TypedContractMethod<[], [bigint], "view">;

  BETA_Y2: TypedContractMethod<[], [bigint], "view">;

  DELTA_X1: TypedContractMethod<[], [bigint], "view">;

  DELTA_X2: TypedContractMethod<[], [bigint], "view">;

  DELTA_Y1: TypedContractMethod<[], [bigint], "view">;

  DELTA_Y2: TypedContractMethod<[], [bigint], "view">;

  GAMMA_X1: TypedContractMethod<[], [bigint], "view">;

  GAMMA_X2: TypedContractMethod<[], [bigint], "view">;

  GAMMA_Y1: TypedContractMethod<[], [bigint], "view">;

  GAMMA_Y2: TypedContractMethod<[], [bigint], "view">;

  IC0_X: TypedContractMethod<[], [bigint], "view">;

  IC0_Y: TypedContractMethod<[], [bigint], "view">;

  IC10_X: TypedContractMethod<[], [bigint], "view">;

  IC10_Y: TypedContractMethod<[], [bigint], "view">;

  IC11_X: TypedContractMethod<[], [bigint], "view">;

  IC11_Y: TypedContractMethod<[], [bigint], "view">;

  IC12_X: TypedContractMethod<[], [bigint], "view">;

  IC12_Y: TypedContractMethod<[], [bigint], "view">;

  IC13_X: TypedContractMethod<[], [bigint], "view">;

  IC13_Y: TypedContractMethod<[], [bigint], "view">;

  IC14_X: TypedContractMethod<[], [bigint], "view">;

  IC14_Y: TypedContractMethod<[], [bigint], "view">;

  IC15_X: TypedContractMethod<[], [bigint], "view">;

  IC15_Y: TypedContractMethod<[], [bigint], "view">;

  IC16_X: TypedContractMethod<[], [bigint], "view">;

  IC16_Y: TypedContractMethod<[], [bigint], "view">;

  IC17_X: TypedContractMethod<[], [bigint], "view">;

  IC17_Y: TypedContractMethod<[], [bigint], "view">;

  IC18_X: TypedContractMethod<[], [bigint], "view">;

  IC18_Y: TypedContractMethod<[], [bigint], "view">;

  IC19_X: TypedContractMethod<[], [bigint], "view">;

  IC19_Y: TypedContractMethod<[], [bigint], "view">;

  IC1_X: TypedContractMethod<[], [bigint], "view">;

  IC1_Y: TypedContractMethod<[], [bigint], "view">;

  IC20_X: TypedContractMethod<[], [bigint], "view">;

  IC20_Y: TypedContractMethod<[], [bigint], "view">;

  IC21_X: TypedContractMethod<[], [bigint], "view">;

  IC21_Y: TypedContractMethod<[], [bigint], "view">;

  IC22_X: TypedContractMethod<[], [bigint], "view">;

  IC22_Y: TypedContractMethod<[], [bigint], "view">;

  IC23_X: TypedContractMethod<[], [bigint], "view">;

  IC23_Y: TypedContractMethod<[], [bigint], "view">;

  IC24_X: TypedContractMethod<[], [bigint], "view">;

  IC24_Y: TypedContractMethod<[], [bigint], "view">;

  IC2_X: TypedContractMethod<[], [bigint], "view">;

  IC2_Y: TypedContractMethod<[], [bigint], "view">;

  IC3_X: TypedContractMethod<[], [bigint], "view">;

  IC3_Y: TypedContractMethod<[], [bigint], "view">;

  IC4_X: TypedContractMethod<[], [bigint], "view">;

  IC4_Y: TypedContractMethod<[], [bigint], "view">;

  IC5_X: TypedContractMethod<[], [bigint], "view">;

  IC5_Y: TypedContractMethod<[], [bigint], "view">;

  IC6_X: TypedContractMethod<[], [bigint], "view">;

  IC6_Y: TypedContractMethod<[], [bigint], "view">;

  IC7_X: TypedContractMethod<[], [bigint], "view">;

  IC7_Y: TypedContractMethod<[], [bigint], "view">;

  IC8_X: TypedContractMethod<[], [bigint], "view">;

  IC8_Y: TypedContractMethod<[], [bigint], "view">;

  IC9_X: TypedContractMethod<[], [bigint], "view">;

  IC9_Y: TypedContractMethod<[], [bigint], "view">;

  P_TOTAL_SIZE: TypedContractMethod<[], [bigint], "view">;

  SCALAR_FIELD_SIZE: TypedContractMethod<[], [bigint], "view">;

  verifyProof: TypedContractMethod<
    [
      pointA_: [BigNumberish, BigNumberish],
      pointB_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pointC_: [BigNumberish, BigNumberish],
      publicSignals_: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALPHA_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ALPHA_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_FIELD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BETA_X1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BETA_X2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BETA_Y1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BETA_Y2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DELTA_X1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DELTA_X2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DELTA_Y1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DELTA_Y2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAMMA_X1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAMMA_X2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAMMA_Y1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAMMA_Y2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC0_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC0_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC10_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC10_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC11_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC11_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC12_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC12_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC13_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC13_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC14_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC14_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC15_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC15_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC16_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC16_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC17_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC17_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC18_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC18_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC19_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC19_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC1_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC1_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC20_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC20_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC21_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC21_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC22_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC22_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC23_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC23_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC24_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC24_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC2_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC2_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC3_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC3_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC4_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC4_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC5_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC5_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC6_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC6_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC7_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC7_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC8_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC8_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC9_X"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "IC9_Y"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "P_TOTAL_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCALAR_FIELD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [
      pointA_: [BigNumberish, BigNumberish],
      pointB_: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pointC_: [BigNumberish, BigNumberish],
      publicSignals_: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
