/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRegistrationVerifier,
  IRegistrationVerifierInterface,
} from "../../../../contracts/interfaces/verifiers/IRegistrationVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "pointA_",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "pointB_",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "pointC_",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[5]",
        name: "publicSignals_",
        type: "uint256[5]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRegistrationVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistrationVerifierInterface {
    return new Interface(_abi) as IRegistrationVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRegistrationVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRegistrationVerifier;
  }
}
