/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITransferVerifier,
  ITransferVerifierInterface,
} from "../../../../contracts/interfaces/verifiers/ITransferVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "pointA_",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "pointB_",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "pointC_",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[32]",
        name: "publicSignals_",
        type: "uint256[32]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITransferVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ITransferVerifierInterface {
    return new Interface(_abi) as ITransferVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITransferVerifier {
    return new Contract(address, _abi, runner) as unknown as ITransferVerifier;
  }
}
