/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWithdrawVerifier,
  IWithdrawVerifierInterface,
} from "../../../../contracts/interfaces/verifiers/IWithdrawVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "pointA_",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "pointB_",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "pointC_",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[16]",
        name: "publicSignals_",
        type: "uint256[16]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWithdrawVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IWithdrawVerifierInterface {
    return new Interface(_abi) as IWithdrawVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWithdrawVerifier {
    return new Contract(address, _abi, runner) as unknown as IWithdrawVerifier;
  }
}
