/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEncryptedERC,
  IEncryptedERCInterface,
} from "../../../contracts/interfaces/IEncryptedERC";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256[7]",
        name: "pct",
        type: "uint256[7]",
      },
    ],
    name: "setUserBalancePCT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEncryptedERC__factory {
  static readonly abi = _abi;
  static createInterface(): IEncryptedERCInterface {
    return new Interface(_abi) as IEncryptedERCInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEncryptedERC {
    return new Contract(address, _abi, runner) as unknown as IEncryptedERC;
  }
}
