/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRegistrar,
  IRegistrarInterface,
} from "../../../contracts/interfaces/IRegistrar";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserPublicKey",
    outputs: [
      {
        internalType: "uint256[2]",
        name: "publicKey",
        type: "uint256[2]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isUserRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRegistrar__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistrarInterface {
    return new Interface(_abi) as IRegistrarInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRegistrar {
    return new Contract(address, _abi, runner) as unknown as IRegistrar;
  }
}
